### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by martybalandis** [njasm/soundcloud#14]
I stumbled accross this library which is quite recent and from description is exactly what I need, however, there is not a single FULL example how to use it. 

I have included a path to Soundcloud.php and SoundcloudFacade.php. And i get error Class not found so I used "use Njasm\Soundcloud\SoundcloudFacade;" and php IDE highlighted error goes away but all I get is blank page. If I use debug. 

So my main problem is figuring out how to include your library. Shouldn't it have a autoloader or something?

This is what I have:

require_once '../../classes/Soundcloud/Soundcloud.php';
require_once '../../classes/Soundcloud/SoundcloudFacade.php';

use Njasm\Soundcloud\SoundcloudFacade; 

$clientID = '12345678';
$clientSecret = '12345678910';
$callbackUri = 'http://mycallback/callback.html';

$facade = new SoundcloudFacade($clientID, $clientSecret, $callbackUri);
$url = $facade->getAuthUrl();

// or inject your specific request params
$url = $facade->getAuthUrl(
    array(
        'response_type' => 'code',
        'scope' => '*',
        'state' => 'my_app_state_code'
    )
);

I am using: PHP 5.5.3 on debian.
Thank you

**Comment by njasm** [comment]
@martybalandis any news with this code ?

**Comment by martybalandis** [comment]
@njasm In the end I made the official library working. I am sure this would come in handy for someone else who would want to use the code.

**Comment by njasm** [comment]
@martybalandis ok, thanks for your input. :+1:  
We'll provide an autoload to be included if developers arent using composer in they projects.

**Comment by njasm** [comment]
merged! 
@martybalandis thank you for your input and feedback.
