### ISSUE TITLE
create library own autoloader for projects not using composer

### ISSUE THREAD

**Issue by njasm** [njasm/soundcloud#15]
if more developers are not using composer as they dependency manager and trying to work with this library.

we might provide some autoloader for the library in the future..
related to #14

**Comment by bratzelk** [comment]
Hey, thanks for the good work so far.
+1 for this issue as I'm not using composer in my stack.

**Comment by njasm** [comment]
Hi @bratzelk , can you tell me if you are using the provided code in the issue #14 ? If so, can you tell me if everything is working as expected for your use cases ? 

Since it seems some developers are not working with composer, we'll provide an autoloader.php to be included by developers in they own projects.

Thanks for your time.

**Comment by njasm** [comment]
merged

**Comment by njasm** [comment]
@bratzelk thanks for your input.
