### ISSUE TITLE
How to use Autoload

### ISSUE THREAD

**Issue by noveweb** [njasm/soundcloud#20]
Hi, Guy!

My application is running on the folder: /admin/
The Njasm library is on the folder: /admin/classes/Soundcloud/
The test file is /admin/soundcloud.php

How can i use the library on the file soundcloud.php ?
Where i put the file autoload.php?

Actual try:
<?php
require("autoload.php");
use Njasm\Soundcloud\SoundcloudFacade;

$facade = new SoundcloudFacade("xxxx", "xxxx", "xxxx");
$url = $facade->getAuthUrl();
echo $url;

Actual error:

Fatal error: Class 'Njasm\Soundcloud\SoundcloudFacade' not found in /home/noveweb/public_html/admin/soundcloud.php on line 5

Thanks in advance!

**Comment by njasm** [comment]
Hi @noveweb 

You ``MUST download ALL the files from the library`` from github, (download the ZIP and uncompress).
You must not move files from the library around, and with the step above you don't need to.

The autoloader is expecting the same folder structure that you find in the Git Repository. so you have to
 download the files from the master branch (ALL the Files without changing the folder STRUCTURE) use the github feature that github provides to you on the page of the repository.

folder structure:

 /admin/classes/Soundcloud/
    |--> Auth/
    |--> Factory/
    |--> Request/
    |--> Resource/
    |--> UrlBuilder/
    |--> Soundcloud.php
    |--> SoundcloudFacade.php
    |--> autoload.php


now from ``/admin/test.php`` you include the ``autoload.php`` from the library and everything should work as expected.

tell me how it went.

**Comment by noveweb** [comment]
Obrigado, Nelson!!!

Agora funcionou perfeitamente. 

Abraços do colega Brasileiro,
Tiago Barbosa

**Comment by njasm** [comment]
@noveweb ok, fico contente em saber que ficou resolvido! 

Outro grande abraço Tiago! :)
