### ISSUE TITLE
Add track to Playlist

### ISSUE THREAD

**Issue by cdev38399** [njasm/soundcloud#23]
Add track to Playlist works once, but then I got 500 - Internal Server Error for the next add track to playlist and its never works again since.

**Comment by njasm** [comment]
@cdev38399 where do you get the 500 ? on you server or from the soundcloud server?

Can you post the code you're using to add tracks to playlist?

**Comment by cdev38399** [comment]
Guess, its from SC server
Please help to check out below code
I'm using version 2.2.2

Thanks

     public function actionArtwork($id)
     {
         $model = new UploadForm();

         if (Yii::$app->request->isPost) {
             $model->file = UploadedFile::getInstance($model, 'file');

             if ($model->file && $model->validate()) {
if($model->file->saveAs('/home/xxx/yyy/artworks/' . 
$model->file->baseName . '.' . $model->file->extension))
                 {
                     $facade = $this->connectSoundCloud();

                     $trackPath = '/home/xxx/yyy/artworks/' . 
$model->file->baseName . '.' . $model->file->extension;

                     $artwork_data = array(
                         'track'=> array(
                             'artwork_data'=>  $trackPath
                         )
                     );

                     $err_msg = '';
                     $response = $facade->put('/tracks/' . $id, 
$artwork_data)->request();
                     $response_obj = $response->bodyObject();
                     if($response_obj->errors){
                         $errors = array();
                         foreach($response_obj->errors as $v){
                             $errors[] = $v->error_message;
                         }
                         $err_msg = implode(", ", $errors);
                     }

                     return $this->redirect(array('index', 
'err_msg'=>$err_msg ));
                 }
             }
         }

         return $this->render('upload_artwork', array('model' => $model));
     }

**Comment by cdev38399** [comment]
Opps #23 is closed as its works already
Above code if for #24.
