### ISSUE TITLE
Upload Artwork

### ISSUE THREAD

**Issue by cdev38399** [njasm/soundcloud#24]
Tried to upload artwork image 

$params = array(
   'track'=> array(
      'artwork_data'=> $artworkFullPath
    )
);
$response = $facade->put('/tracks/' . $track_id, $params)->request();

Error message => Uploaded file is missing (even I double check the file is there)

Is there any correct way to update artwork?

**Comment by njasm** [comment]
what version of ``PHP`` are you using?
what content is in ``$artworkFullPath`` variable?

**Comment by cdev38399** [comment]
PHP v5.4
|$artworkFullPath is fullpath of the image file => string|

**Comment by njasm** [comment]
try this..
```php 
$params = array(
'track'=> array(
'artwork_data'=> new \CurlFile($artworkFullPath)
)
);
$response = $facade->put('/tracks/' . $track_id, $params)->request();
```

**Comment by cdev38399** [comment]
It returns  404 - Not Found

**Comment by njasm** [comment]
I've edited the comment, have you seen it?

**Comment by cdev38399** [comment]
I tried this but still giving the same error => Upload file missing (not 
404-Not Found as my previous comment)

$params = array(
'track'=> array(
'artwork_data'=> new \CurlFile($artworkFullPath)
)
);
$response = $facade->put('/tracks/' . $track_id, $params)->request();

**Comment by njasm** [comment]
acording to the documentation you can only use
``
asset_data 	binary data of the audio file 	(only for uploading``
``
artwork_data 	binary data of the artwork image 	(only for uploading)
``
for uploading ``post`` requests, no updates via api of images.

reference : https://developers.soundcloud.com/docs/api/reference#tracks
