### ISSUE TITLE
"Last Request Content-Type isn't application/json."

### ISSUE THREAD

**Issue by marcpages** [njasm/soundcloud#25]
Hi, I'm getting an error when trying to run this example. It was working before.

```php
       $clientID = "(hidden)";
	$clientSecret = "(hidden)";
	$username = "(hidden)";
	$password = "(hidden)";


	$facade = new SoundcloudFacade($clientID, $clientSecret);
	$facade->userCredentials($username, $password); // on success, access_token is set by default for next requests.
	$response = $facade->get('/me')->request();
	// raw/string body response
	echo $response->bodyRaw();
	// as object
	echo $response->bodyObject()->id;
	// as array
	$array = $response->bodyArray();

```
Fatal error: Uncaught exception 'OutOfBoundsException' with message 'Last Request Content-Type isn't application/json.' in /home/radiolescala/www/intranet/api/soundcloud/Soundcloud/Request/Response.php:87 Stack trace: #0 /home/radiolescala/www/intranet/api/soundcloud/Soundcloud/SoundcloudFacade.php(60): Njasm\Soundcloud\Request\Response->bodyObject() #1 /home/radiolescala/www/intranet/api/soundcloud/test.php(24): Njasm\Soundcloud\SoundcloudFacade->userCredentials('(hidden)', '(hidden)') #2 {main} thrown in /home/radiolescala/www/intranet/api/soundcloud/Soundcloud/Request/Response.php on line 87

**Comment by BruceWouaigne** [comment]
I'm getting the same error using `getAuthToken()`. The exact same code was working 2 days ago.

**Comment by njasm** [comment]
@BruceWouaigne @marcpages  what versions you guys using stable/ master??

**Comment by njasm** [comment]
is anyone using a web-app that redirect a user to the Soundcloud authorization page and then back without using user credentials flow? They documentation doesn't talk anymore about userCredential flow... I don't know if they removed it...

we need codeForToken exchange without using credentialFlow.

**Comment by njasm** [comment]
Password credentials flow is working. Thested wwith my golang library.

Also found problems with curl and soundcloud on stackoverflow. 

http://stackoverflow.com/questions/32898394/soundcloud-oauth2-token-returning-nothing-but-a-401-response

**Comment by iadj** [comment]
Same problem here.

**Comment by cdev38399** [comment]
same problem

**Comment by njasm** [comment]
Ok, I've found the issue.

For some reason the last "out of the blue" deployment of soundcloud oauth server does not allow anymore to send a POST with a content-type of application/json while requesting (and maybe refreshing tokens).

This was the way we where requesting for a token, setting content-type: application/json by default and adding the payload of the post as a json object 
``{ "client_id": "XXXX", "client_secret": "YYYYY", etc }`` 

I'm changing the methods that request/refreshes tokens in forcing to use ``application/x-www-form-urlencoded`` as the content-type to use.

I'll need your help to test this fix, and see if everything is working as expected, like commenting, uploading, download, etc..

**Comment by njasm** [comment]
@marcpages @BruceWouaigne @iadj @cdev38399 @pulkitjalan latest master have the fix.. if you find that everything is working as expected please report back so we can tag it to a stable release 2.2.3.

thanks all for the report.

**Comment by pulkitjalan** [comment]
@njasm Thanks! Fix seems to work for me

**Comment by njasm** [comment]
@pulkitjalan that's great. have you tried creating a comment, uploading a track, creating a web-profiles or even updating the user profile with the latest master?

**Comment by cdev38399** [comment]
Wow, it works.
Great job, thanks a lot :)

**Comment by pulkitjalan** [comment]
@njasm I have only tested connecting and uploading a track and both are working fine. I do not make use of comments or creating/updating profiles in my system so have not tested those. Thanks.

**Comment by marcpages** [comment]
@njasm It's working now! Tested it with uploading a track and getting my tracks.
Thanks a lot!

**Comment by njasm** [comment]
Ok, thank you all for the feedback, fix was tagged to version 2.2.3.

**Comment by BruceWouaigne** [comment]
Awesome @njasm tanks a lot!

**Comment by hyanmandian** [comment]
same problem

**Comment by a7madgamal** [comment]
awesome
can you please update the docs with the new example because the current docs didn't work for me :)
