### ISSUE TITLE
I am getting this error while I trying to login 

### ISSUE THREAD

**Issue by bluesuiter** [njasm/soundcloud#30]
OutOfBoundsException Object ( [message:protected] => Last Request Content-Type isn't application/json. [string:Exception:private] => [code:protected] => 0 [file:protected] => /nfs/c09/h01/mnt/209908/domains/musichighcourt.com/html/soundcloudapp/Soundcloud/Request/Response.php [line:protected] => 87 [trace:Exception:private] => Array ( [0] => Array ( [file] => /nfs/c09/h01/mnt/209908/domains/musichighcourt.com/html/soundcloudapp/Soundcloud/SoundcloudFacade.php [line] => 88 [function] => bodyObject [class] => Njasm\Soundcloud\Request\Response [type] => -> [args] => Array ( ) ) [1] => Array ( [file] => /nfs/c09/h01/mnt/209908/domains/musichighcourt.com/html/soundcloudapp/user_callback.php [line] => 27 [function] => codeForToken [class] => Njasm\Soundcloud\SoundcloudFacade [type] => -> [args] => Array ( [0] => a2b4a6e72e0f058d5cb111e47ca611c6 ) ) ) [previous:Exception:private] => ) Some Error Occurred,Try Again

**Comment by bluesuiter** [comment]
[soundcloud-master.zip](https://github.com/njasm/soundcloud/files/162664/soundcloud-master.zip)

**Comment by njasm** [comment]
hi @bluesuiter , I'm unable to replicate you problem. can you provide the block of code that you have to login - that is throwing the OutOfBoundsException?

And also paste ``var_dump($response->bodyRaw()); var_dump($response->getHeaders());``

**Comment by bluesuiter** [comment]
[user_callback.txt](https://github.com/njasm/soundcloud/files/163054/user_callback.txt)

**Comment by bluesuiter** [comment]
I am not getting any of the response from sound cloud

**Comment by bluesuiter** [comment]
bodyRaw
string(0) ""

getHeaders
array(8) {
  ["Access-Control-Allow-Headers"]=>
  string(43) "Accept, Authorization, Content-Type, Origin"
  ["Access-Control-Allow-Methods"]=>
  string(22) "GET, PUT, POST, DELETE"
  ["Access-Control-Allow-Origin"]=>
  string(1) "*"
  ["Access-Control-Expose-Headers"]=>
  string(4) "Date"
  ["Cache-Control"]=>
  string(35) "private, max-age=0, must-revalidate"
  ["Date"]=>
  string(29) "Tue, 08 Mar 2016 11:57:25 GMT"
  ["Server"]=>
  string(4) "am/2"
  ["Content-Length"]=>
  string(1) "0"
}

**Comment by njasm** [comment]
I still cannot replicate it...please download the latest master and try again..
btw you are doin it 'wrong'..

try this code with latest version and tell me if it works.
**Note: this code is not secure/safe. it's just for testing only, you should note use this code as is in production**
```php
// variables declared above...
 $facade = new SoundcloudFacade($clientID, $clientSecret, $callbackUri);
if (isset($_GET['code'])) {
    echo "Code is : " . $_GET['code'] . "<br>";
    $response = $facade->codeForToken($_GET['code']);
    echo "token: " . $response->bodyObject()->access_token . "<br>";
    echo "scope: " . $response->bodyObject()->scope . "<br>";
    var_dump($facade->get('/me')->request());
    exit;
}
```

**Comment by njasm** [comment]
@bluesuiter any luck with that?

**Comment by bluesuiter** [comment]
Yes, I resolved the issue. Many Thanks for your concern.
Please let me know can I make the song like and re-post on Sound-Cloud using API.

**Comment by njasm** [comment]
I don't know what you mean by like and re-post..
Take a look at the official api docs, https://developers.soundcloud.com/


Glad you sort it out.

**Comment by bluesuiter** [comment]
Thank You for your great work, I sorted it out this issue also. It's a great API  :)
