### ISSUE TITLE
"error_message":"422 - Unprocessable Entity"

### ISSUE THREAD

**Issue by diaa-saada** [njasm/soundcloud#31]
I downloaded the source from github today 2016/April/02

I tried this code 

`$facade = new SoundcloudFacade( 'xxxxx', 'yyyy' );
        $facade->userCredentials("xxx@gmail.com"  , "ppppp"); 
$trackPath = '/var/www/radio/2016/04/06/Gender/4/160402133210x.mp3';
        $params = array('track[name]' => 'Cool remix');
        $response = $facade->upload($trackPath, $params);
        var_dump( $response ) ;

and the response was

object(Njasm\Soundcloud\Request\Response)#89 (9) {
  ["httpVersion":"Njasm\Soundcloud\Request\Response":private]=>
  string(8) "HTTP/1.1"
  ["httpCode":"Njasm\Soundcloud\Request\Response":private]=>
  string(3) "422"
  ["httpCodeString":"Njasm\Soundcloud\Request\Response":private]=>
  string(21) "Unprocessable Entity
"
  ["response":"Njasm\Soundcloud\Request\Response":private]=>
  string(496) "HTTP/1.1 100 Continue

HTTP/1.1 422 Unprocessable Entity
Access-Control-Allow-Headers: Accept, Authorization, Content-Type, Origin
Access-Control-Allow-Methods: GET, PUT, POST, DELETE
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Date
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Sat, 02 Apr 2016 11:37:22 GMT
Server: am/2
Status: 422 Unprocessable Entity
Content-Length: 59

{"errors":[{"error_message":"422 - Unprocessable Entity"}]}"
  ["info":"Njasm\Soundcloud\Request\Response":private]=>
  array(23) {
    ["url"]=>
    string(33) "https://api.soundcloud.com/tracks"
    ["content_type"]=>
    string(31) "application/json; charset=utf-8"
    ["http_code"]=>
    int(422)
    ["header_size"]=>
    int(437)
    ["request_size"]=>
    int(368)
    ["filetime"]=>
    int(-1)
    ["ssl_verify_result"]=>
    int(0)
    ["redirect_count"]=>
    int(0)
    ["total_time"]=>
    float(0.125724)
    ["namelookup_time"]=>
    float(1.7E-5)
    ["connect_time"]=>
    float(0.00414)
    ["pretransfer_time"]=>
    float(0.016218)
    ["size_upload"]=>
    float(298931)
    ["size_download"]=>
    float(59)
    ["speed_download"]=>
    float(469)
    ["speed_upload"]=>
    float(2377676)
    ["download_content_length"]=>
    float(59)
    ["upload_content_length"]=>
    float(298931)
    ["starttransfer_time"]=>
    float(0.020478)
    ["redirect_time"]=>
    float(0)
    ["redirect_url"]=>
    string(0) ""
    ["primary_ip"]=>
    string(14) "93.184.220.127"
    ["certinfo"]=>
    array(0) {
    }
  }
  ["errno":"Njasm\Soundcloud\Request\Response":private]=>
  int(0)
  ["errorString":"Njasm\Soundcloud\Request\Response":private]=>
  string(0) ""
  ["headers":"Njasm\Soundcloud\Request\Response":private]=>
  array(10) {
    ["Access-Control-Allow-Headers"]=>
    string(43) "Accept, Authorization, Content-Type, Origin"
    ["Access-Control-Allow-Methods"]=>
    string(22) "GET, PUT, POST, DELETE"
    ["Access-Control-Allow-Origin"]=>
    string(1) "*"
    ["Access-Control-Expose-Headers"]=>
    string(4) "Date"
    ["Cache-Control"]=>
    string(8) "no-cache"
    ["Content-Type"]=>
    string(31) "application/json; charset=utf-8"
    ["Date"]=>
    string(29) "Sat, 02 Apr 2016 11:37:22 GMT"
    ["Server"]=>
    string(4) "am/2"
    ["Status"]=>
    string(24) "422 Unprocessable Entity"
    ["Content-Length"]=>
    string(2) "59"
  }
  ["body":"Njasm\Soundcloud\Request\Response":private]=>
  string(59) "{"errors":[{"error_message":"422 - Unprocessable Entity"}]}"
}

I tried the download code it worked but the upload gives this problem
I tried to find  a solution but no luck
the tracks I'm trying to upload are valid MP3 files without copyright

From SoundCloud Doc
422 Unprocessable Entity
The request was valid, but one or more of the parameters looks a little screwy. It's possible that you sent data in the wrong format. One example would be providing an array when we expected a string.
so what might by the problem  ?

**Comment by njasm** [comment]
hello @diaa-saada,
tell me what version of the library you have (check ``Soundcloud.php`` constants for that information)?
What's the size of the mp3 file you're trying to upload in MB?

It' might be a bug in the lib, you're not using the latest lib version or some weird api upgrade that broke upload again.. this is not the first time, it happen before #19 .
Send me that information and we'll try to confirm this issue of yours as soon as I get home.

**Comment by diaa-saada** [comment]
thanks for the reply @njasm 
const VERSION = '2.2.3';

I've tried more than one mp3 file some of them I recorded my self
4.5MB , 1.9MB , 5.2 MB

**Comment by njasm** [comment]
hello @diaa-saada 

I've tested the upload, and I cannot replicate your error with the latest master branch. :/

code used for testing...
```php
$track = [
    'title' => 'sample sound with arwork...',
    'downloadable' => true,
    'artwork_data' => new \CURLFile(__DIR__ . '/../image1.jpg')
];

$response = $soundcloud->upload(__DIR__ . '/../sample.mp3', $track);
var_dump($response->bodyRaw())
```
can you try again to see if it was something with soundcloud?

**Comment by diaa-saada** [comment]
thanks
the params in the examples page is a bit diffrent it woks now

**Comment by njasm** [comment]
yes, the readme is wrong! 
there's no ``name`` param in the track, it's ``title`` need to fix that.
