### ISSUE TITLE
can't get it to update a track's artwork

### ISSUE THREAD

**Issue by alexpcoleman** [njasm/soundcloud#32]
According to the SC API docs, you should be able to do it with a simple PUT request: https://developers.soundcloud.com/docs/api/guide#updating-metadata

I just can't get it to work. Name & description PUT updates work fine, but the artwork update does not. Here's my code snippet:

```
$thumbnail = 'http://example.com/some-image.png';
$thumbnailData = file_get_contents($thumbnail);
$updateResponse = $api
        ->put($trackUrl, [ 'track' => ['artwork_data' => $thumbnailData] ])
        ->request();
```

Thoughts? Do you have a working example of this by chance?

**Comment by njasm** [comment]
hello @alexpcoleman 

try this..

```php
$thumbnail = '/local/file/some-image.png';
$updateResponse = $api
        ->put($trackUrl, 
                ['track' => 
                        ['artwork_data' => new \CurlFile($thumbnailData)]
                ]
        )->request([CURLOPT_HTTPHEADER => ['Content-Type: multipart/form-data']]);
```

and tell me if it worked.

**Comment by alexpcoleman** [comment]
No luck, unfortunately. I modified `getBodyContent()` in `Request.php` as follows in order to get it to process the `multipart/form-data`:

```
// ...
        if (!!array_intersect(['Content-Type: multipart/form-data', 'Content-Type: application/x-www-form-urlencoded'],
            $this->options[CURLOPT_HTTPHEADER])) {
            return http_build_query($this->resource->getParams());
        }
// ...
```

...but it still returns a `Uploaded file is missing` error.

**Comment by njasm** [comment]
@alexpcoleman I've wrongly interpreted you question. 
Thought you were uploading the track and cover. but you want to update an existing track's cover, and that is not allowed by Soundcloud API.

check issue #24 for more info.
