### ISSUE TITLE
Uploading Track - community share parameter

### ISSUE THREAD

**Issue by Perpleex** [njasm/soundcloud#34]
Hello,

I search for sometime now the good syntax to share and upload on facebook and twitter.

On soundcloud the doc is erratic.

They have a reference on Python,Js api but nothing on http reference guide.
https://developers.soundcloud.com/docs/api/guide#uploading

Actually i have try syntax with : 
share_to > connections >array(id_connection);
share_to >array(id_connection);
Post_to >connections > array(id connection);
Post_to > array(id connection);

In most case i break when  wrapper parse parameter.
Because at a time i need to put an array of connections in third layer and the parse can't handle that.

Have you ever use this functionnality and what the good syntax ?

Ps: i don't find how to tag this issue for discussion

**Comment by njasm** [comment]
Hi @Perpleex 

from the ruby example, have you tried something like this ?

```php
$trackPath = '/home/njasm/great.mp3';
$params = [
    'title' => 'Cool remix',
    // more track parameters here,
    'shared_to' => [
        ['connections' => [
            ['id' => 1234], // twitter connection id
            ['id' => 4321] // facebook connection id
        ]
    ]
];
$response = $facade->upload($trackPath, $params);
```

**Comment by Perpleex** [comment]
I have already test this syntax
Here [StackTrace](http://pastebin.com/4dQ8MgYE) Actually at the level of array a conversion type prevent the parse.

And a param debug export :
array (
  'track[title]' => 'Un programme 2016/05/19',
  'track[artwork_data]' => 
  CURLFile::__set_state(array(
     'name' => 'C:\\Users\\Perpleex\\Documents\\RadioPaisLaraval\\public/filemanager/userfiles/laravel-l-slant.png',
     'mime' => '',
     'postname' => '',
  )),
  'track[description]' => 'qsdqsdqsd
',
  'tag_list' => 'Unprogramme Radio RadioPais',
  'label_name' => 'RadioPais',
  'genre' => 'Unprogramme',
  'shared_to' => 
  array (
    'connections' => 
    array (
      0 => 
      array (
        'id' => 144229805,
      ),
      1 => 
      array (
        'id' => 137362238,
      ),
    ),
  ),
)
