### ISSUE TITLE
Undefined offset: 1 in /Soundcloud/Request/Response.php:34

### ISSUE THREAD

**Issue by iadj** [njasm/soundcloud#37]
New issue that's occuring since today. Apparently SoundCloud changed something which causes `codeForToken($code)` to no longer work and returns an error: `Undefined offset: 1 in /Soundcloud/Request/Response.php:34`

**Comment by iadj** [comment]
The issue might have been resolved. It seems like it was temporary. Will report back tomorrow.

**Comment by njasm** [comment]
ok cool, thanks!

**Comment by njasm** [comment]
@iadj any news on this one?

**Comment by njasm** [comment]
ping @iadj

**Comment by macrowish** [comment]
@njasm The issue hasn't persisted since it disappeared

**Comment by iadj** [comment]
@njasm The issue hasn't persisted

**Comment by njasm** [comment]
👍 ok. good. thanks!
