### ISSUE TITLE
Manually authorising

### ISSUE THREAD

**Issue by shealan** [njasm/soundcloud#38]
In my app I have already stored the users token.

How can I use that to make calls to the Soundcloud API with this library without having to reauthorise them using the flow detailed in the docs?

**Comment by njasm** [comment]
if by token your say the access token, you just need to call ``setAccessToken`` https://github.com/njasm/soundcloud/blob/master/src/Soundcloud/Soundcloud.php#L82
before any other API Call and that access token will be used, take care that access token expire.

**Comment by njasm** [comment]
@shealan any luck it that ?

**Comment by njasm** [comment]
lack of user feedback... and old one.
