### ISSUE TITLE
Get does not follow redirects

### ISSUE THREAD

**Issue by tylergets** [njasm/soundcloud#41]
When requesting /resolve with a url, I receive the 302 as a response not the actual object. What is the underlying http library, it appears to not be following redirects

**Comment by njasm** [comment]
no uderlying library, it's pure php curl.
https://github.com/njasm/soundcloud/blob/master/src/Soundcloud/Request/Request.php

can you provide a code sample to replicate your problem?
thanks

**Comment by njasm** [comment]
ping @tylergets

**Comment by njasm** [comment]
unable to reproduce.

**Comment by adamazad** [comment]
You can pass `CURLOPT_FOLLOWLOCATION` to `request()`  as follows:

```
$response = $soundcloud->get('/resolve', ['url' => $url])->request([CURLOPT_FOLLOWLOCATION => true]);
```
