### ISSUE TITLE
update metadata of a track 

### ISSUE THREAD

**Issue by tuxcoffee** [njasm/soundcloud#43]
Hello here, i'm trying update metadata of a track, but always i got error 
`[{"error_message":"403 - Forbidden"}]}`

i tried many combinations..

`$this->soundCloud->put('/tracks/' . $trackId, [
                'description' => 'ssssooo',
            ])->request());    `

no

`$this->soundCloud->put('/tracks/' . $trackId, ['track' => [
                'description' => 'ssssooo',
            ]])->request());   `

no

`$this->soundCloud->put('/tracks/' . $trackId, [
                'track[description]' => 'ssssooo',
            ])->request());    `

no

HOW? thanks :-)

**Comment by njasm** [comment]
@tuxcoffee  I'm sorry but I cannot replicate your issue with the latest master branch.

by the error message I would say that you're trying to update a track that does not belong to the authenticated user or you are not even authenticated at all.

I've run the following code and successfully updated the description of a track of mine..
```php
$clientID = "123456...."; 
$clientSecret = "a65h3h46...";
$soundcloud = new \Njasm\Soundcloud\SoundcloudFacade($clientID, $clientSecret);
$response = $soundcloud->userCredentials("user@example.code.com", "killerpassword");
$track = [
    'track' => ['description' => 'test description']
];

$trackId = '12345667899'; // track owned by user@example.code.com
$response = $soundcloud->put('/tracks/' . $trackId, $track)->request();

// after update, lets check it (PS I've also confirmed by logging in the web platform)
$response = $soundcloud->get('/tracks/' . $trackId)->request();
var_dump($response->bodyObject()->description); // string(16) "test description"
```
tell me if this piece of code helped!

**Comment by tuxcoffee** [comment]
yes, you are right, the syntax is correct and i really did mistake in authentication, thanks :-)
